[package]
name = "rust-sql-engine"
version = "0.0.1-SNAPSHOT"
authors = ["Alex-Diez <alexvic.amatory@gmail.com>"]

[lib]
name = "sql"
path = "src/sql/sql.rs"

[[test]]
name = "unit_tests"
path = "src/tests/unit_tests.rs"
